/*
	SDZDeviceServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZDeviceServiceExample.h"
#import "SDZDeviceService.h"
#import "APPObject.h"

@implementation SDZDeviceServiceExample

- (void)run {
	// Create the service
	SDZDeviceService* service = [SDZDeviceService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

//	// Returns BOOL. 
//	[service IncrementAppVisitCount:self action:@selector(IncrementAppVisitCountHandler:) appname: @"" deviceType: @""];
//
//	// Returns BOOL. 
//	[service SaveSharedJoke:self action:@selector(SaveSharedJokeHandler:) target: @"" subject: @"" joke: @"" sharedby: @"" sharedfrom: @"" deviceType: @""];

	// Returns NSString*. 
            NSString *udid = [APPObject createUUID];
            udid = [udid stringByReplacingOccurrencesOfString:@"-" withString:@""];
    
	[service Savedeviceinfo:self action:@selector(SavedeviceinfoHandler:) deviceId: udid appName: @"IPhoneBuildADis"];
}

	

// Handle the response from IncrementAppVisitCount.
		
- (void) IncrementAppVisitCountHandler: (BOOL) value {
			

	// Do something with the BOOL result
		
			
}
	

// Handle the response from SaveSharedJoke.
		
- (void) SaveSharedJokeHandler: (BOOL) value {
			

	// Do something with the BOOL result
		
			
}
	

// Handle the response from Savedeviceinfo.
		
- (void) SavedeviceinfoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
			
}
	

@end
		